name: CI

on: [pull_request, push]

jobs:
  build:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Build and Verify
        run: |
          yarn install --frozen-lockfile
          yarn test
  detect-publish:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    outputs:
      publish: ${{ steps.detect_publish.outputs.publish }}
    steps:
      - uses: actions/checkout@v2
      - id: detect_publish
        run: |
          result=$(./scripts/detect_publish.sh)
          echo $result
          echo ::set-output name=publish::$result
  publish:
    runs-on: ubuntu-latest
    needs: [detect-publish]
    if: needs.detect-publish.outputs.publish == 1 && github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          scope: '@vertexvis'
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          yarn install --frozen-lockfile
          yarn test
          ./scripts/publish.sh
